"""python-docx accessible Word document exporter."""

import os
from datetime import date

from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

from core.models import TranscriptModel
from utils.time_utils import seconds_to_display_time, format_duration


# Brand colors as RGB tuples
PRIMARY_RGB = RGBColor(0xA2, 0x3B, 0x84)
SECONDARY_RGB = RGBColor(0x3A, 0x2B, 0x95)
ACCENT_RGB = RGBColor(0x6F, 0x2F, 0xA6)
TIMESTAMP_RGB = RGBColor(0x9B, 0x7F, 0xC4)
TEXT_RGB = RGBColor(0x00, 0x00, 0x00)


def export_docx(model: TranscriptModel, output_path: str, spanish: bool = False):
    """Export transcript as accessible Word document.

    Args:
        model: The transcript model with segments.
        output_path: Path to write the DOCX file.
        spanish: If True, use Spanish text (text_es) where available.
    """
    doc = Document()

    # Set document properties
    core = doc.core_properties
    core.author = "Dr. Rocco G. Catrone"
    core.title = "La Mia Scribe Transcript"
    core.subject = "Transcript"
    core.language = "es" if spanish else "en"

    # Set default font
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Arial"
    font.size = Pt(11)
    font.color.rgb = TEXT_RGB

    # Heading 1: File name + date
    source_name = os.path.basename(model.source_file) if model.source_file else "Unknown"
    today = date.today().strftime("%Y-%m-%d")
    duration = format_duration(model.duration_seconds)

    h1 = doc.add_heading(f"{source_name} — {today}", level=1)
    for run in h1.runs:
        run.font.color.rgb = SECONDARY_RGB

    # Metadata paragraph
    meta = doc.add_paragraph()
    meta_run = meta.add_run(
        f"Duration: {duration}  |  Model: {model.whisper_model_used}  |  "
        f"Language: {model.language_detected or 'Unknown'}"
    )
    meta_run.font.size = Pt(10)
    meta_run.font.color.rgb = RGBColor(0x6A, 0x6A, 0x8E)

    # Summary section (if available)
    if model.summary:
        h2 = doc.add_heading("Summary", level=2)
        for run in h2.runs:
            run.font.color.rgb = ACCENT_RGB

        summary_para = doc.add_paragraph()
        summary_run = summary_para.add_run(model.summary)
        summary_run.font.italic = True
        summary_run.font.size = Pt(11)

        if model.key_points:
            for point in model.key_points:
                bullet = doc.add_paragraph(style="List Bullet")
                bullet_run = bullet.add_run(point)
                bullet_run.font.size = Pt(11)

    # Transcript section
    h3 = doc.add_heading("Transcript", level=2)
    for run in h3.runs:
        run.font.color.rgb = ACCENT_RGB

    for seg in model.segments:
        para = doc.add_paragraph()

        # Timestamp (bold)
        start = seconds_to_display_time(seg.start_time)
        end = seconds_to_display_time(seg.end_time)
        ts_run = para.add_run(f"[{start} \u2192 {end}]  ")
        ts_run.font.bold = True
        ts_run.font.color.rgb = TIMESTAMP_RGB
        ts_run.font.size = Pt(11)

        # Speaker label
        if seg.speaker:
            speaker_run = para.add_run(f"{seg.speaker}:  ")
            speaker_run.font.bold = True
            speaker_run.font.color.rgb = ACCENT_RGB
            speaker_run.font.size = Pt(11)

        # Transcript text
        text = (seg.text_es if spanish and seg.text_es else seg.text)
        text_run = para.add_run(text)
        text_run.font.size = Pt(11)
        text_run.font.color.rgb = TEXT_RGB

    # Footer paragraph
    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer.add_run(
        f"Generated by La Mia Scribe — Tech Inclusion Pro — {today}"
    )
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(0x6A, 0x6A, 0x8E)

    doc.save(output_path)
