"""ReportLab branded PDF exporter for La Mia Scribe."""

import os
from datetime import date

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor, white, black
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER

from core.models import TranscriptModel
from utils.time_utils import seconds_to_display_time, format_duration


# Brand colors
PRIMARY = HexColor("#a23b84")
SECONDARY = HexColor("#3a2b95")
ACCENT = HexColor("#6f2fa6")
TIMESTAMP_COLOR = HexColor("#9b7fc4")
TEXT_COLOR = HexColor("#000000")


def _build_styles():
    """Create paragraph styles for the PDF."""
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        name="BrandTitle",
        fontName="Helvetica-Bold",
        fontSize=18,
        textColor=white,
        alignment=TA_CENTER,
        spaceAfter=4,
    ))

    styles.add(ParagraphStyle(
        name="BrandSubtitle",
        fontName="Helvetica",
        fontSize=11,
        textColor=white,
        alignment=TA_CENTER,
        spaceAfter=0,
    ))

    styles.add(ParagraphStyle(
        name="MetaInfo",
        fontName="Helvetica",
        fontSize=10,
        textColor=TEXT_COLOR,
        spaceAfter=2,
        leading=14,
    ))

    styles.add(ParagraphStyle(
        name="SectionHeading",
        fontName="Helvetica-Bold",
        fontSize=14,
        textColor=SECONDARY,
        spaceBefore=16,
        spaceAfter=8,
    ))

    styles.add(ParagraphStyle(
        name="SummaryText",
        fontName="Helvetica-Oblique",
        fontSize=11,
        textColor=TEXT_COLOR,
        spaceAfter=6,
        leading=15,
    ))

    styles.add(ParagraphStyle(
        name="KeyPoint",
        fontName="Helvetica",
        fontSize=11,
        textColor=TEXT_COLOR,
        leftIndent=20,
        spaceAfter=3,
        leading=14,
        bulletIndent=10,
    ))

    styles.add(ParagraphStyle(
        name="TranscriptLine",
        fontName="Helvetica",
        fontSize=11,
        textColor=TEXT_COLOR,
        spaceAfter=6,
        leading=15,
    ))

    styles.add(ParagraphStyle(
        name="Timestamp",
        fontName="Helvetica",
        fontSize=11,
        textColor=TIMESTAMP_COLOR,
    ))

    styles.add(ParagraphStyle(
        name="Footer",
        fontName="Helvetica",
        fontSize=8,
        textColor=HexColor("#6a6a8e"),
        alignment=TA_CENTER,
    ))

    return styles


def _header_footer(canvas, doc):
    """Draw page footer with page number and branding."""
    canvas.saveState()
    page_num = canvas.getPageNumber()
    footer_text = (
        f"Page {page_num}  |  Generated by La Mia Scribe  |  "
        f"{date.today().strftime('%Y-%m-%d')}"
    )
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(HexColor("#6a6a8e"))
    canvas.drawCentredString(
        letter[0] / 2, 0.5 * inch, footer_text
    )
    canvas.restoreState()


def export_pdf(model: TranscriptModel, output_path: str, spanish: bool = False):
    """Export transcript as branded PDF.

    Args:
        model: The transcript model with segments.
        output_path: Path to write the PDF file.
        spanish: If True, use Spanish text (text_es) where available.
    """
    styles = _build_styles()
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        title="La Mia Scribe Transcript",
        author="Dr. Rocco G. Catrone",
        subject="Transcript",
        creator="La Mia Scribe — Tech Inclusion Pro",
    )

    story = []

    # Header gradient block (simulated with a colored table)
    header_data = [
        [Paragraph("La Mia Scribe", styles["BrandTitle"])],
        [Paragraph("Tech Inclusion Pro", styles["BrandSubtitle"])],
    ]
    header_table = Table(header_data, colWidths=[doc.width])
    header_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), PRIMARY),
        ("TOPPADDING", (0, 0), (-1, 0), 16),
        ("BOTTOMPADDING", (0, -1), (-1, -1), 16),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROUNDEDCORNERS", [6, 6, 6, 6]),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 16))

    # Metadata block
    source_name = os.path.basename(model.source_file) if model.source_file else "Unknown"
    today = date.today().strftime("%Y-%m-%d")
    duration = format_duration(model.duration_seconds)

    meta_text = (
        f"<b>File:</b> {source_name}<br/>"
        f"<b>Date:</b> {today}<br/>"
        f"<b>Duration:</b> {duration}<br/>"
        f"<b>Whisper Model:</b> {model.whisper_model_used}<br/>"
        f"<b>Language:</b> {model.language_detected or 'Unknown'}"
    )
    story.append(Paragraph(meta_text, styles["MetaInfo"]))
    story.append(Spacer(1, 12))

    # Summary section
    if model.summary:
        story.append(Paragraph("Summary", styles["SectionHeading"]))
        story.append(Paragraph(model.summary, styles["SummaryText"]))

        if model.key_points:
            story.append(Spacer(1, 6))
            for point in model.key_points:
                story.append(Paragraph(
                    f"\u2022  {point}", styles["KeyPoint"]
                ))
        story.append(Spacer(1, 12))

    # Transcript section
    story.append(Paragraph("Transcript", styles["SectionHeading"]))

    for seg in model.segments:
        start = seconds_to_display_time(seg.start_time)
        text = (seg.text_es if spanish and seg.text_es else seg.text)

        timestamp_str = f'<font color="#9b7fc4">[{start}]</font>  '
        speaker_str = ""
        if seg.speaker:
            speaker_str = f'<font color="#6f2fa6"><b>{seg.speaker}:</b></font>  '

        line = f"{timestamp_str}{speaker_str}{text}"
        story.append(Paragraph(line, styles["TranscriptLine"]))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
