"""Translation strings for La Mia Scribe — 23 languages."""

LANGUAGE_OPTIONS = [
    ("en", "English"),
    ("zh", "中文 (Chinese)"),
    ("hi", "हिन्दी (Hindi)"),
    ("es", "Español (Spanish)"),
    ("fr", "Français (French)"),
    ("ar", "العربية (Arabic)"),
    ("bn", "বাংলা (Bengali)"),
    ("pt", "Português (Portuguese)"),
    ("ru", "Русский (Russian)"),
    ("ur", "اردو (Urdu)"),
    ("id", "Bahasa Indonesia"),
    ("de", "Deutsch (German)"),
    ("ja", "日本語 (Japanese)"),
    ("pcm", "Naijá (Nigerian Pidgin)"),
    ("arz", "مصري (Egyptian Arabic)"),
    ("mr", "मराठी (Marathi)"),
    ("te", "తెలుగు (Telugu)"),
    ("tr", "Türkçe (Turkish)"),
    ("ta", "தமிழ் (Tamil)"),
    ("yue", "粵語 (Cantonese)"),
    ("vi", "Tiếng Việt (Vietnamese)"),
    ("tl", "Filipino (Tagalog)"),
    ("it", "Italiano (Italian)"),
]

RTL_LANGUAGES = {"ar", "arz", "ur"}

WHISPER_LANGUAGE_MAP = {
    "pcm": "en",
    "arz": "ar",
    "yue": "zh",
}

# Compact format: key -> tuple of 22 strings in LANGUAGE_OPTIONS order
_L = [c for c, _ in LANGUAGE_OPTIONS]

_T = {
# ── Navigation ──
"dashboard": ("Dashboard", "仪表板", "डैशबोर्ड", "Panel", "Tableau de bord", "لوحة القيادة", "ড্যাশবোর্ড", "Painel", "Панель", "ڈیش بورڈ", "Dasbor", "Übersicht", "ダッシュボード", "Dashboard", "لوحة التحكم", "डॅशबोर्ड", "డాష్‌బోర్డ్", "Kontrol Paneli", "டாஷ்போர்டு", "儀表板", "Bảng điều khiển", "Dashboard", 'Pannello'),
"tutorial": ("Tutorial", "教程", "ट्यूटोरियल", "Tutorial", "Tutoriel", "دليل الاستخدام", "টিউটোরিয়াল", "Tutorial", "Руководство", "ٹیوٹوریل", "Panduan", "Anleitung", "チュートリアル", "Tutorial", "شرح الاستخدام", "मार्गदर्शिका", "ట్యుటోరియల్", "Öğretici", "பயிற்சி", "教學", "Hướng dẫn", "Gabay", 'Tutorial'),
"sign_out": ("Sign Out", "退出", "लॉग आउट", "Cerrar sesión", "Déconnexion", "تسجيل الخروج", "সাইন আউট", "Sair", "Выйти", "سائن آؤٹ", "Keluar", "Abmelden", "ログアウト", "Sign Out", "تسجيل الخروج", "बाहेर पडा", "సైన్ అవుట్", "Çıkış", "வெளியேறு", "登出", "Đăng xuất", "Mag-sign out", 'Esci'),
"welcome": ("Welcome, {name}", "欢迎，{name}", "स्वागत है, {name}", "Bienvenido/a, {name}", "Bienvenue, {name}", "مرحباً، {name}", "স্বাগতম, {name}", "Bem-vindo/a, {name}", "Добро пожаловать, {name}", "خوش آمدید، {name}", "Selamat datang, {name}", "Willkommen, {name}", "ようこそ、{name}", "Welcome, {name}", "أهلاً، {name}", "स्वागत, {name}", "స్వాగతం, {name}", "Hoş geldiniz, {name}", "வரவேற்கிறோம், {name}", "歡迎，{name}", "Chào mừng, {name}", "Maligayang pagdating, {name}", 'Benvenuto/a, {name}'),

# ── Left Panel ──
"drop_zone": ("Drag & drop media file here\nor use Browse below", "将媒体文件拖放到此处\n或点击下方浏览", "मीडिया फ़ाइल यहाँ खींचें\nया नीचे ब्राउज़ करें", "Arrastra un archivo aquí\no usa Examinar", "Glissez un fichier ici\nou cliquez Parcourir", "اسحب ملف الوسائط هنا\nأو استخدم تصفح", "মিডিয়া ফাইল এখানে টানুন\nবা ব্রাউজ করুন", "Arraste um arquivo aqui\nou use Procurar", "Перетащите файл сюда\nили нажмите Обзор", "میڈیا فائل یہاں ڈریگ کریں\nیا براؤز کریں", "Seret file media ke sini\natau klik Telusuri", "Mediendatei hierher ziehen\noder Durchsuchen", "ファイルをここにドロップ\nまたは参照を使用", "Drop media file here\nor use Browse below", "اسحب ملف الميديا هنا\nأو استخدم تصفح", "मीडिया फाइल इथे ड्रॅग करा\nकिंवा ब्राउझ करा", "మీడియా ఫైల్ ఇక్కడ డ్రాప్ చేయండి\nలేదా బ్రౌజ్ చేయండి", "Medya dosyasını buraya sürükleyin\nveya Gözat'ı kullanın", "மீடியா கோப்பை இங்கே இழுக்கவும்\nஅல்லது உலாவுக", "將媒體檔案拖放到此處\n或點擊下方瀏覽", "Kéo thả tệp vào đây\nhoặc dùng Duyệt", "I-drag ang file dito\no gamitin ang Browse", 'Trascina un file multimediale qui\no usa Sfoglia'),
"browse_file": ("Browse File", "浏览文件", "फ़ाइल ब्राउज़ करें", "Examinar", "Parcourir", "تصفح الملفات", "ফাইল ব্রাউজ", "Procurar", "Обзор", "فائل براؤز کریں", "Telusuri File", "Datei suchen", "ファイルを参照", "Browse File", "تصفح الملفات", "फाइल ब्राउझ करा", "ఫైల్ బ్రౌజ్", "Dosya Gözat", "கோப்பு உலாவு", "瀏覽檔案", "Duyệt tệp", "Mag-browse", 'Sfoglia File'),
"youtube_url": ("YouTube URL:", "YouTube 链接：", "YouTube URL:", "URL de YouTube:", "URL YouTube :", "رابط يوتيوب:", "YouTube URL:", "URL do YouTube:", "Ссылка YouTube:", "YouTube URL:", "URL YouTube:", "YouTube-Link:", "YouTube URL:", "YouTube URL:", "لينك يوتيوب:", "YouTube URL:", "YouTube URL:", "YouTube URL:", "YouTube URL:", "YouTube 連結：", "URL YouTube:", "YouTube URL:", 'URL YouTube:'),
"fetch": ("Fetch", "获取", "प्राप्त करें", "Obtener", "Récupérer", "جلب", "আনুন", "Obter", "Загрузить", "حاصل کریں", "Ambil", "Abrufen", "取得", "Fetch", "جيب", "मिळवा", "పొందండి", "Getir", "பெறு", "獲取", "Tải", "Kunin", 'Scarica'),
"local_file": ("Local File:", "本地文件：", "स्थानीय फ़ाइल:", "Archivo local:", "Fichier local :", "ملف محلي:", "স্থানীয় ফাইল:", "Arquivo local:", "Локальный файл:", "مقامی فائل:", "File Lokal:", "Lokale Datei:", "ローカルファイル:", "Local File:", "ملف محلي:", "स्थानिक फाइल:", "స్థానిక ఫైల్:", "Yerel Dosya:", "உள்ளூர் கோப்பு:", "本地檔案：", "Tệp cục bộ:", "Lokal na file:", 'File Locale:'),
"file_url_input": ("File / URL Input", "文件/URL 输入", "फ़ाइल / URL इनपुट", "Archivo / URL", "Fichier / URL", "إدخال ملف / رابط", "ফাইল / URL ইনপুট", "Arquivo / URL", "Файл / URL", "فائل / URL", "Input File / URL", "Datei / URL", "ファイル / URL 入力", "File / URL Input", "إدخال ملف / لينك", "फाइल / URL इनपुट", "ఫైల్ / URL ఇన్‌పుట్", "Dosya / URL Girişi", "கோப்பு / URL உள்ளீடு", "檔案 / URL 輸入", "Nhập tệp / URL", "File / URL Input", 'File / URL'),
"whisper_settings": ("Whisper Settings", "Whisper 设置", "Whisper सेटिंग्स", "Configuración Whisper", "Paramètres Whisper", "إعدادات Whisper", "Whisper সেটিংস", "Configurações Whisper", "Настройки Whisper", "Whisper ترتیبات", "Pengaturan Whisper", "Whisper-Einstellungen", "Whisper 設定", "Whisper Settings", "إعدادات Whisper", "Whisper सेटिंग्ज", "Whisper సెట్టింగ్‌లు", "Whisper Ayarları", "Whisper அமைப்புகள்", "Whisper 設定", "Cài đặt Whisper", "Whisper Settings", 'Impostazioni Whisper'),
"model_size": ("Model Size:", "模型大小：", "मॉडल साइज़:", "Tamaño del modelo:", "Taille du modèle :", "حجم النموذج:", "মডেল সাইজ:", "Tamanho do modelo:", "Размер модели:", "ماڈل سائز:", "Ukuran Model:", "Modellgröße:", "モデルサイズ:", "Model Size:", "حجم الموديل:", "मॉडेल आकार:", "మోడల్ పరిమాణం:", "Model Boyutu:", "மாதிரி அளவு:", "模型大小：", "Kích thước mô hình:", "Laki ng Model:", 'Dimensione Modello:'),
"language": ("Language:", "语言：", "भाषा:", "Idioma:", "Langue :", "اللغة:", "ভাষা:", "Idioma:", "Язык:", "زبان:", "Bahasa:", "Sprache:", "言語:", "Language:", "اللغة:", "भाषा:", "భాష:", "Dil:", "மொழி:", "語言：", "Ngôn ngữ:", "Wika:", 'Lingua:'),
"device": ("Device:", "设备：", "डिवाइस:", "Dispositivo:", "Appareil :", "الجهاز:", "ডিভাইস:", "Dispositivo:", "Устройство:", "ڈیوائس:", "Perangkat:", "Gerät:", "デバイス:", "Device:", "الجهاز:", "डिव्हाइस:", "పరికరం:", "Cihaz:", "சாதனம்:", "裝置：", "Thiết bị:", "Device:", 'Dispositivo:'),
"compute_type": ("Compute Type:", "计算类型：", "कंप्यूट प्रकार:", "Tipo de cómputo:", "Type de calcul :", "نوع الحساب:", "কম্পিউট টাইপ:", "Tipo de computação:", "Тип вычислений:", "کمپیوٹ ٹائپ:", "Tipe Komputasi:", "Rechentyp:", "計算タイプ:", "Compute Type:", "نوع الحساب:", "कंप्यूट प्रकार:", "కంప్యూట్ రకం:", "Hesaplama Türü:", "கணக்கீட்டு வகை:", "計算類型：", "Loại tính toán:", "Uri ng Compute:", 'Tipo di Calcolo:'),
"transcribe": ("Transcribe", "转录", "ट्रांसक्राइब", "Transcribir", "Transcrire", "نسخ", "ট্রান্সক্রাইব", "Transcrever", "Транскрибировать", "ٹرانسکرائب", "Transkrip", "Transkribieren", "文字起こし", "Transcribe", "نسخ", "ट्रान्सक्राइब", "ట్రాన్స్‌క్రైబ్", "Yazıya Dök", "படியெடு", "轉錄", "Phiên âm", "I-transcribe", 'Trascrivi'),
"cancel": ("Cancel", "取消", "रद्द करें", "Cancelar", "Annuler", "إلغاء", "বাতিল", "Cancelar", "Отмена", "منسوخ کریں", "Batal", "Abbrechen", "キャンセル", "Cancel", "إلغاء", "रद्द करा", "రద్దు", "İptal", "ரத்து", "取消", "Hủy", "Kanselahin", 'Annulla'),
"clear": ("Clear", "清除", "साफ़ करें", "Limpiar", "Effacer", "مسح", "মুছুন", "Limpar", "Очистить", "صاف کریں", "Hapus", "Löschen", "クリア", "Clear", "مسح", "साफ करा", "క్లియర్", "Temizle", "அழி", "清除", "Xóa", "I-clear", 'Pulisci'),
"ollama_optional": ("Ollama (Optional)", "Ollama（可选）", "Ollama (वैकल्पिक)", "Ollama (Opcional)", "Ollama (Optionnel)", "Ollama (اختياري)", "Ollama (ঐচ্ছিক)", "Ollama (Opcional)", "Ollama (необязательно)", "Ollama (اختیاری)", "Ollama (Opsional)", "Ollama (Optional)", "Ollama（オプション）", "Ollama (Optional)", "Ollama (اختياري)", "Ollama (पर्यायी)", "Ollama (ఐచ్ఛికం)", "Ollama (İsteğe Bağlı)", "Ollama (விருப்பம்)", "Ollama（可選）", "Ollama (Tùy chọn)", "Ollama (Opsyonal)", 'Ollama (Opzionale)'),
"clean_fillers": ("Clean up filler words", "清理填充词", "फिलर शब्द हटाएँ", "Limpiar muletillas", "Supprimer les mots de remplissage", "إزالة كلمات الحشو", "ফিলার শব্দ পরিষ্কার", "Limpar palavras de preenchimento", "Убрать слова-паразиты", "فلر الفاظ صاف کریں", "Bersihkan kata pengisi", "Füllwörter entfernen", "フィラーワードを除去", "Clean up filler words", "شيل كلمات الحشو", "फिलर शब्द काढा", "ఫిల్లర్ పదాలు తొలగించు", "Dolgu kelimeleri temizle", "நிரப்பு சொற்கள் நீக்கு", "清理填充詞", "Xóa từ đệm", "Linisin ang filler words", 'Pulisci parole riempitive'),
"generate_summary": ("Generate summary & key points", "生成摘要和要点", "सारांश और मुख्य बिंदु बनाएँ", "Generar resumen y puntos clave", "Générer un résumé et points clés", "إنشاء ملخص ونقاط رئيسية", "সারাংশ ও মূল পয়েন্ট তৈরি", "Gerar resumo e pontos-chave", "Создать резюме и тезисы", "خلاصہ اور اہم نکات بنائیں", "Buat ringkasan & poin utama", "Zusammenfassung erstellen", "要約とキーポイントを生成", "Make summary & key points", "اعمل ملخص ونقاط رئيسية", "सारांश आणि मुख्य मुद्दे तयार करा", "సారాంశం & కీ పాయింట్లు", "Özet ve ana noktalar oluştur", "சுருக்கம் & முக்கிய புள்ளிகள்", "生成摘要和要點", "Tạo tóm tắt & điểm chính", "Gumawa ng buod at pangunahing punto", 'Genera riepilogo e punti chiave'),
"translate_spanish": ("Translate to Spanish", "翻译为西班牙语", "स्पैनिश में अनुवाद करें", "Traducir al español", "Traduire en espagnol", "ترجمة إلى الإسبانية", "স্প্যানিশে অনুবাদ", "Traduzir para espanhol", "Перевести на испанский", "ہسپانوی میں ترجمہ", "Terjemahkan ke Spanyol", "Ins Spanische übersetzen", "スペイン語に翻訳", "Translate to Spanish", "ترجم للإسباني", "स्पॅनिशमध्ये अनुवाद", "స్పానిష్‌లోకి అనువదించు", "İspanyolcaya çevir", "ஸ்பானிஷில் மொழிபெயர்", "翻譯為西班牙語", "Dịch sang tiếng Tây Ban Nha", "Isalin sa Espanyol", 'Traduci in spagnolo'),
"label_speakers": ("Label speakers", "标记说话者", "वक्ताओं को लेबल करें", "Etiquetar hablantes", "Identifier les intervenants", "تسمية المتحدثين", "স্পিকার লেবেল", "Identificar falantes", "Отметить спикеров", "اسپیکرز لیبل کریں", "Beri label pembicara", "Sprecher kennzeichnen", "話者をラベル付け", "Label speakers", "سمي المتكلمين", "वक्ते लेबल करा", "స్పీకర్లను లేబుల్ చేయి", "Konuşmacıları etiketle", "பேச்சாளர்களை லேபிளிடு", "標記說話者", "Gán nhãn người nói", "Lagyan ng label ang speakers", 'Etichetta parlanti'),
"ollama_model": ("Ollama Model:", "Ollama 模型：", "Ollama मॉडल:", "Modelo Ollama:", "Modèle Ollama :", "نموذج Ollama:", "Ollama মডেল:", "Modelo Ollama:", "Модель Ollama:", "Ollama ماڈل:", "Model Ollama:", "Ollama-Modell:", "Ollama モデル:", "Ollama Model:", "موديل Ollama:", "Ollama मॉडेल:", "Ollama మోడల్:", "Ollama Modeli:", "Ollama மாதிரி:", "Ollama 模型：", "Mô hình Ollama:", "Ollama Model:", 'Modello Ollama:'),
"auto_detect": ("Auto-detect", "自动检测", "स्वतः पहचान", "Autodetectar", "Détection auto", "كشف تلقائي", "স্বয়ংক্রিয় শনাক্ত", "Autodetectar", "Автоопределение", "خود کار شناخت", "Deteksi otomatis", "Automatisch", "自動検出", "Auto-detect", "كشف تلقائي", "स्वयं ओळख", "ఆటో-డిటెక్ట్", "Otomatik algıla", "தானியங்கு கண்டறி", "自動偵測", "Tự phát hiện", "Auto-detect", 'Rilevamento automatico'),
"transcript_lang": ("Transcript Language", "转录语言", "ट्रांसक्रिप्ट भाषा", "Idioma de transcripción", "Langue de transcription", "لغة النسخ", "ট্রান্সক্রিপ্ট ভাষা", "Idioma da transcrição", "Язык транскрипции", "ٹرانسکرپٹ زبان", "Bahasa Transkrip", "Transkriptsprache", "文字起こし言語", "Transcript Language", "لغة النسخ", "ट्रान्सक्रिप्ट भाषा", "ట్రాన్స్‌క్రిప్ట్ భాష", "Transkript Dili", "படியெடுப்பு மொழி", "轉錄語言", "Ngôn ngữ phiên âm", "Wika ng Transcript", 'Lingua Trascrizione'),

# ── Transcript Viewer ──
"find": ("Find:", "查找：", "खोजें:", "Buscar:", "Rechercher :", "بحث:", "খুঁজুন:", "Buscar:", "Найти:", "تلاش:", "Cari:", "Suchen:", "検索:", "Find:", "بحث:", "शोधा:", "కనుగొను:", "Bul:", "கண்டுபிடி:", "搜尋：", "Tìm:", "Hanapin:", 'Cerca:'),
"replace_label": ("Replace:", "替换：", "बदलें:", "Reemplazar:", "Remplacer :", "استبدال:", "প্রতিস্থাপন:", "Substituir:", "Заменить:", "تبدیل:", "Ganti:", "Ersetzen:", "置換:", "Replace:", "استبدال:", "बदला:", "భర్తీ:", "Değiştir:", "மாற்று:", "替換：", "Thay thế:", "Palitan:", 'Sostituisci:'),
"next_btn": ("Next", "下一个", "अगला", "Siguiente", "Suivant", "التالي", "পরবর্তী", "Próximo", "Далее", "اگلا", "Berikut", "Weiter", "次へ", "Next", "التالي", "पुढील", "తదుపరి", "Sonraki", "அடுத்து", "下一個", "Tiếp", "Susunod", 'Successivo'),
"prev_btn": ("Prev", "上一个", "पिछला", "Anterior", "Précédent", "السابق", "পূর্ববর্তী", "Anterior", "Назад", "پچھلا", "Sebelum", "Zurück", "前へ", "Prev", "السابق", "मागील", "మునుపటి", "Önceki", "முந்தைய", "上一個", "Trước", "Nakaraan", 'Precedente'),
"replace_btn": ("Replace", "替换", "बदलें", "Reemplazar", "Remplacer", "استبدال", "প্রতিস্থাপন", "Substituir", "Заменить", "تبدیل", "Ganti", "Ersetzen", "置換", "Replace", "استبدال", "बदला", "భర్తీ", "Değiştir", "மாற்று", "替換", "Thay thế", "Palitan", 'Sostituisci'),
"close": ("Close", "关闭", "बंद करें", "Cerrar", "Fermer", "إغلاق", "বন্ধ", "Fechar", "Закрыть", "بند کریں", "Tutup", "Schließen", "閉じる", "Close", "قفل", "बंद करा", "మూసివేయి", "Kapat", "மூடு", "關閉", "Đóng", "Isara", 'Chiudi'),
"show_english": ("English", "英语", "अंग्रेज़ी", "Inglés", "Anglais", "إنجليزي", "ইংরেজি", "Inglês", "Английский", "انگریزی", "Inggris", "Englisch", "英語", "English", "إنجليزي", "इंग्रजी", "ఆంగ్లం", "İngilizce", "ஆங்கிலம்", "英語", "Tiếng Anh", "Ingles", 'Inglese'),
"show_spanish": ("Spanish", "西班牙语", "स्पैनिश", "Español", "Espagnol", "إسباني", "স্প্যানিশ", "Espanhol", "Испанский", "ہسپانوی", "Spanyol", "Spanisch", "スペイン語", "Spanish", "إسباني", "स्पॅनिश", "స్పానిష్", "İspanyolca", "ஸ்பானிஷ்", "西班牙語", "Tiếng Tây Ban Nha", "Espanyol", 'Spagnolo'),
"words_count": ("Words: {w}  |  Characters: {c}", "词数: {w}  |  字符: {c}", "शब्द: {w}  |  वर्ण: {c}", "Palabras: {w}  |  Caracteres: {c}", "Mots : {w}  |  Caractères : {c}", "كلمات: {w}  |  أحرف: {c}", "শব্দ: {w}  |  অক্ষর: {c}", "Palavras: {w}  |  Caracteres: {c}", "Слов: {w}  |  Символов: {c}", "الفاظ: {w}  |  حروف: {c}", "Kata: {w}  |  Karakter: {c}", "Wörter: {w}  |  Zeichen: {c}", "単語: {w}  |  文字: {c}", "Words: {w}  |  Characters: {c}", "كلمات: {w}  |  حروف: {c}", "शब्द: {w}  |  अक्षरे: {c}", "పదాలు: {w}  |  అక్షరాలు: {c}", "Kelime: {w}  |  Karakter: {c}", "சொற்கள்: {w}  |  எழுத்துகள்: {c}", "詞數: {w}  |  字元: {c}", "Từ: {w}  |  Ký tự: {c}", "Salita: {w}  |  Karakter: {c}", 'Parole: {w}  |  Caratteri: {c}'),
"show_log": ("\u25bc Show Log", "\u25bc 显示日志", "\u25bc लॉग दिखाएँ", "\u25bc Mostrar registro", "\u25bc Afficher le journal", "\u25bc عرض السجل", "\u25bc লগ দেখান", "\u25bc Mostrar log", "\u25bc Показать журнал", "\u25bc لاگ دکھائیں", "\u25bc Tampilkan Log", "\u25bc Protokoll anzeigen", "\u25bc ログを表示", "\u25bc Show Log", "\u25bc عرض السجل", "\u25bc लॉग दाखवा", "\u25bc లాగ్ చూపు", "\u25bc Günlüğü Göster", "\u25bc பதிவு காட்டு", "\u25bc 顯示日誌", "\u25bc Hiện nhật ký", "\u25bc Ipakita ang Log", '▼ Mostra Log'),
"hide_log": ("\u25b2 Hide Log", "\u25b2 隐藏日志", "\u25b2 लॉग छुपाएँ", "\u25b2 Ocultar registro", "\u25b2 Masquer le journal", "\u25b2 إخفاء السجل", "\u25b2 লগ লুকান", "\u25b2 Ocultar log", "\u25b2 Скрыть журнал", "\u25b2 لاگ چھپائیں", "\u25b2 Sembunyikan Log", "\u25b2 Protokoll ausblenden", "\u25b2 ログを非表示", "\u25b2 Hide Log", "\u25b2 إخفاء السجل", "\u25b2 लॉग लपवा", "\u25b2 లాగ్ దాచు", "\u25b2 Günlüğü Gizle", "\u25b2 பதிவு மறை", "\u25b2 隱藏日誌", "\u25b2 Ẩn nhật ký", "\u25b2 Itago ang Log", '▲ Nascondi Log'),

# ── Export ──
"export_formats": ("Export Formats:", "导出格式：", "निर्यात प्रारूप:", "Formatos de exportación:", "Formats d'export :", "صيغ التصدير:", "এক্সপোর্ট ফরম্যাট:", "Formatos de exportação:", "Форматы экспорта:", "برآمد فارمیٹ:", "Format Ekspor:", "Exportformate:", "エクスポート形式:", "Export Formats:", "صيغ التصدير:", "निर्यात स्वरूपे:", "ఎగుమతి ఫార్మాట్లు:", "Dışa Aktarma Biçimleri:", "ஏற்றுமதி வடிவங்கள்:", "匯出格式：", "Định dạng xuất:", "Mga Format ng Export:", 'Formati di Esportazione:'),
"save_selected": ("Save Selected Formats", "保存选定格式", "चयनित प्रारूप सहेजें", "Guardar formatos", "Enregistrer les formats", "حفظ الصيغ المحددة", "নির্বাচিত ফরম্যাট সংরক্ষণ", "Salvar formatos", "Сохранить выбранные", "منتخب فارمیٹ محفوظ کریں", "Simpan Format Terpilih", "Ausgewählte speichern", "選択形式を保存", "Save Selected Formats", "احفظ الصيغ المختارة", "निवडलेले स्वरूप जतन करा", "ఎంచుకున్న ఫార్మాట్లు సేవ్", "Seçili Biçimleri Kaydet", "தேர்ந்தெடுத்தவை சேமி", "儲存所選格式", "Lưu định dạng đã chọn", "I-save ang mga napili", 'Salva Formati Selezionati'),
"copy_transcript": ("Copy Transcript to Clipboard", "复制到剪贴板", "क्लिपबोर्ड पर कॉपी करें", "Copiar al portapapeles", "Copier dans le presse-papiers", "نسخ إلى الحافظة", "ক্লিপবোর্ডে কপি", "Copiar para área de transferência", "Копировать в буфер", "کلپ بورڈ پر کاپی", "Salin ke Clipboard", "In Zwischenablage kopieren", "クリップボードにコピー", "Copy to Clipboard", "انسخ للحافظة", "क्लिपबोर्डवर कॉपी", "క్లిప్‌బోర్డ్‌కు కాపీ", "Panoya Kopyala", "கிளிப்போர்டுக்கு நகலெடு", "複製到剪貼板", "Sao chép vào clipboard", "Kopyahin sa Clipboard", 'Copia Trascrizione negli Appunti'),
"export_lang": ("Export:", "导出：", "निर्यात:", "Exportar:", "Exporter :", "تصدير:", "এক্সপোর্ট:", "Exportar:", "Экспорт:", "برآمد:", "Ekspor:", "Export:", "エクスポート:", "Export:", "تصدير:", "निर्यात:", "ఎగుమతి:", "Dışa Aktar:", "ஏற்றுமதி:", "匯出：", "Xuất:", "I-export:", 'Esporta:'),
"english_only": ("English", "英语", "अंग्रेज़ी", "Inglés", "Anglais", "إنجليزي", "ইংরেজি", "Inglês", "Английский", "انگریزی", "Inggris", "Englisch", "英語", "English", "إنجليزي", "इंग्रजी", "ఆంగ్లం", "İngilizce", "ஆங்கிலம்", "英語", "Tiếng Anh", "Ingles", 'Inglese'),
"spanish_only": ("Spanish", "西班牙语", "स्पैनिश", "Español", "Espagnol", "إسباني", "স্প্যানিশ", "Espanhol", "Испанский", "ہسپانوی", "Spanyol", "Spanisch", "スペイン語", "Spanish", "إسباني", "स्पॅनिश", "స్పానిష్", "İspanyolca", "ஸ்பானிஷ்", "西班牙語", "Tiếng Tây Ban Nha", "Espanyol", 'Spagnolo'),
"both_lang": ("Both", "两者", "दोनों", "Ambos", "Les deux", "كلاهما", "উভয়", "Ambos", "Оба", "دونوں", "Keduanya", "Beide", "両方", "Both", "الاتنين", "दोन्ही", "రెండూ", "İkisi de", "இரண்டும்", "兩者", "Cả hai", "Pareho", 'Entrambi'),
"no_formats": ("No Formats Selected", "未选择格式", "कोई प्रारूप नहीं चुना", "Sin formatos seleccionados", "Aucun format sélectionné", "لم يتم اختيار صيغ", "কোনো ফরম্যাট নির্বাচিত নয়", "Nenhum formato selecionado", "Форматы не выбраны", "کوئی فارمیٹ منتخب نہیں", "Tidak ada format dipilih", "Keine Formate ausgewählt", "形式が未選択", "No Formats Selected", "مفيش صيغ متختارة", "कोणतेही स्वरूप निवडलेले नाही", "ఫార్మాట్లు ఎంచుకోలేదు", "Biçim Seçilmedi", "வடிவங்கள் தேர்வு செய்யப்படவில்லை", "未選擇格式", "Chưa chọn định dạng", "Walang napiling format", 'Nessun Formato Selezionato'),
"select_export_dir": ("Select Export Directory", "选择导出目录", "निर्यात निर्देशिका चुनें", "Seleccionar carpeta", "Sélectionner le dossier", "اختر مجلد التصدير", "এক্সপোর্ট ডিরেক্টরি নির্বাচন", "Selecionar diretório", "Выберите папку", "ایکسپورٹ ڈائریکٹری منتخب کریں", "Pilih Direktori Ekspor", "Exportordner wählen", "エクスポート先を選択", "Select Export Folder", "اختار فولدر التصدير", "निर्यात निर्देशिका निवडा", "ఎగుమతి డైరెక్టరీ ఎంచుకోండి", "Dışa Aktarma Dizinini Seç", "ஏற்றுமதி கோப்புறை தேர்வு", "選擇匯出目錄", "Chọn thư mục xuất", "Pumili ng Export Directory", 'Seleziona Cartella di Esportazione'),
"export_complete": ("Export Complete", "导出完成", "निर्यात पूर्ण", "Exportación completada", "Export terminé", "اكتمل التصدير", "এক্সপোর্ট সম্পন্ন", "Exportação concluída", "Экспорт завершён", "ایکسپورٹ مکمل", "Ekspor Selesai", "Export abgeschlossen", "エクスポート完了", "Export Complete", "التصدير خلص", "निर्यात पूर्ण", "ఎగుమతి పూర్తయింది", "Dışa Aktarma Tamamlandı", "ஏற்றுமதி முடிந்தது", "匯出完成", "Xuất hoàn tất", "Export Kumpleto", 'Esportazione Completata'),
"export_failed": ("Export Failed", "导出失败", "निर्यात विफल", "Exportación fallida", "Échec de l'export", "فشل التصدير", "এক্সপোর্ট ব্যর্থ", "Exportação falhou", "Ошибка экспорта", "ایکسپورٹ ناکام", "Ekspor Gagal", "Export fehlgeschlagen", "エクスポート失敗", "Export Fail", "التصدير فشل", "निर्यात अयशस्वी", "ఎగుమతి విఫలమైంది", "Dışa Aktarma Başarısız", "ஏற்றுமதி தோல்வி", "匯出失敗", "Xuất thất bại", "Nabigo ang Export", 'Esportazione Fallita'),
"select_one_format": ("Please select at least one export format.", "请至少选择一种导出格式。", "कृपया कम से कम एक प्रारूप चुनें।", "Seleccione al menos un formato.", "Veuillez sélectionner au moins un format.", "يرجى اختيار صيغة واحدة على الأقل.", "অনুগ্রহ করে অন্তত একটি ফরম্যাট নির্বাচন করুন।", "Selecione pelo menos um formato.", "Выберите хотя бы один формат.", "براہ کرم کم از کم ایک فارمیٹ منتخب کریں۔", "Silakan pilih setidaknya satu format.", "Bitte wählen Sie mindestens ein Format.", "少なくとも1つの形式を選択してください。", "Abeg select at least one format.", "اختار صيغة واحدة على الأقل.", "कृपया किमान एक स्वरूप निवडा.", "దయచేసి కనీసం ఒక ఫార్మాట్ ఎంచుకోండి.", "Lütfen en az bir biçim seçin.", "குறைந்தது ஒரு வடிவத்தைத் தேர்ந்தெடுக்கவும்.", "請至少選擇一種匯出格式。", "Vui lòng chọn ít nhất một định dạng.", "Pumili ng kahit isang format.", 'Seleziona almeno un formato di esportazione.'),

# ── Dashboard ──
"recent_projects": ("Recent Projects", "近期项目", "हाल के प्रोजेक्ट", "Proyectos recientes", "Projets récents", "المشاريع الحديثة", "সাম্প্রতিক প্রকল্প", "Projetos recentes", "Последние проекты", "حالیہ پروجیکٹس", "Proyek Terbaru", "Letzte Projekte", "最近のプロジェクト", "Recent Projects", "المشاريع الأخيرة", "अलीकडील प्रकल्प", "ఇటీవలి ప్రాజెక్ట్‌లు", "Son Projeler", "சமீபத்திய திட்டங்கள்", "近期項目", "Dự án gần đây", "Mga Kamakailang Proyekto", 'Progetti Recenti'),
"refresh": ("Refresh", "刷新", "रिफ्रेश", "Actualizar", "Actualiser", "تحديث", "রিফ্রেশ", "Atualizar", "Обновить", "ریفریش", "Segarkan", "Aktualisieren", "更新", "Refresh", "تحديث", "रिफ्रेश", "రిఫ్రెష్", "Yenile", "புதுப்பி", "重新整理", "Làm mới", "I-refresh", 'Aggiorna'),
"open_transcript": ("Open Transcript", "打开转录", "ट्रांसक्रिप्ट खोलें", "Abrir transcripción", "Ouvrir la transcription", "فتح النسخ", "ট্রান্সক্রিপ্ট খুলুন", "Abrir transcrição", "Открыть транскрипцию", "ٹرانسکرپٹ کھولیں", "Buka Transkrip", "Transkript öffnen", "文字起こしを開く", "Open Transcript", "افتح النسخ", "ट्रान्सक्रिप्ट उघडा", "ట్రాన్స్‌క్రిప్ట్ తెరువు", "Transkripti Aç", "படியெடுப்பு திற", "開啟轉錄", "Mở phiên âm", "Buksan ang Transcript", 'Apri Trascrizione'),
"note": ("Note:", "备注：", "नोट:", "Nota:", "Note :", "ملاحظة:", "নোট:", "Nota:", "Заметка:", "نوٹ:", "Catatan:", "Notiz:", "メモ:", "Note:", "ملاحظة:", "टीप:", "గమనిక:", "Not:", "குறிப்பு:", "備註：", "Ghi chú:", "Tala:", 'Nota:'),
"no_projects": ("No projects yet. Transcribe a file to get started.", "暂无项目。转录一个文件开始使用。", "अभी कोई प्रोजेक्ट नहीं है। शुरू करने के लिए एक फ़ाइल ट्रांसक्राइब करें।", "Sin proyectos aún. Transcribe un archivo para comenzar.", "Aucun projet. Transcrivez un fichier pour commencer.", "لا توجد مشاريع. انسخ ملفًا للبدء.", "এখনও কোনো প্রকল্প নেই। শুরু করতে একটি ফাইল ট্রান্সক্রাইব করুন।", "Nenhum projeto ainda. Transcreva um arquivo para começar.", "Нет проектов. Транскрибируйте файл, чтобы начать.", "ابھی کوئی پروجیکٹ نہیں۔ شروع کرنے کے لیے فائل ٹرانسکرائب کریں۔", "Belum ada proyek. Transkrip file untuk memulai.", "Keine Projekte. Transkribieren Sie eine Datei.", "プロジェクトがありません。ファイルを文字起こしして始めましょう。", "No project yet. Transcribe one file to start.", "مفيش مشاريع لسه. انسخ ملف عشان تبدأ.", "अद्याप कोणतेही प्रकल्प नाहीत। सुरू करण्यासाठी फाइल ट्रान्सक्राइब करा.", "ఇంకా ప్రాజెక్ట్‌లు లేవు. ప్రారంభించడానికి ఫైల్ ట్రాన్స్‌క్రైబ్ చేయండి.", "Henüz proje yok. Başlamak için bir dosya yazıya dökün.", "இன்னும் திட்டங்கள் இல்லை. தொடங்க ஒரு கோப்பை படியெடுக்கவும்.", "暫無項目。轉錄一個檔案開始使用。", "Chưa có dự án. Phiên âm một tệp để bắt đầu.", "Wala pang proyekto. Mag-transcribe ng file para magsimula.", 'Nessun progetto. Trascrivi un file per iniziare.'),
"delete_project": ("Delete Project", "删除项目", "प्रोजेक्ट हटाएँ", "Eliminar proyecto", "Supprimer le projet", "حذف المشروع", "প্রকল্প মুছুন", "Excluir projeto", "Удалить проект", "پروجیکٹ حذف کریں", "Hapus Proyek", "Projekt löschen", "プロジェクトを削除", "Delete Project", "امسح المشروع", "प्रकल्प हटवा", "ప్రాజెక్ట్ తొలగించు", "Projeyi Sil", "திட்டத்தை நீக்கு", "刪除項目", "Xóa dự án", "Tanggalin ang Proyekto", 'Elimina Progetto'),
"project_deleted": ("Project deleted", "项目已删除", "प्रोजेक्ट हटाया गया", "Proyecto eliminado", "Projet supprimé", "تم حذف المشروع", "প্রকল্প মুছে ফেলা হয়েছে", "Projeto excluído", "Проект удалён", "پروجیکٹ حذف ہو گیا", "Proyek dihapus", "Projekt gelöscht", "プロジェクト削除済み", "Project don delete", "المشروع اتمسح", "प्रकल्प हटवला", "ప్రాజెక్ట్ తొలగించబడింది", "Proje silindi", "திட்டம் நீக்கப்பட்டது", "項目已刪除", "Đã xóa dự án", "Tinanggal ang proyekto", 'Progetto eliminato'),
"delete_confirm": ('Delete "{name}" from history?', '从历史中删除"{name}"？', '"{name}" को इतिहास से हटाएँ?', '¿Eliminar "{name}" del historial?', 'Supprimer « {name} » de l\'historique ?', 'حذف "{name}" من السجل؟', '"{name}" ইতিহাস থেকে মুছবেন?', 'Excluir "{name}" do histórico?', 'Удалить «{name}» из истории?', '"{name}" تاریخ سے حذف کریں؟', 'Hapus "{name}" dari riwayat?', '„{name}" aus dem Verlauf löschen?', '「{name}」を履歴から削除しますか？', 'Delete "{name}" from history?', 'امسح "{name}" من السجل؟', '"{name}" इतिहासातून हटवायचे?', '"{name}" హిస్టరీ నుండి తొలగించాలా?', '"{name}" geçmişten silinsin mi?', '"{name}" வரலாற்றிலிருந்து நீக்கவா?', '從歷史中刪除「{name}」？', 'Xóa "{name}" khỏi lịch sử?', 'Tanggalin ang "{name}" sa history?', 'Eliminare "{name}" dalla cronologia?'),
"transcript_not_available": ("Transcript Not Available", "转录不可用", "ट्रांसक्रिप्ट उपलब्ध नहीं", "Transcripción no disponible", "Transcription non disponible", "النسخ غير متاح", "ট্রান্সক্রিপ্ট উপলব্ধ নয়", "Transcrição indisponível", "Транскрипция недоступна", "ٹرانسکرپٹ دستیاب نہیں", "Transkrip Tidak Tersedia", "Transkript nicht verfügbar", "文字起こし利用不可", "Transcript No Dey", "النسخ مش متاح", "ट्रान्सक्रिप्ट उपलब्ध नाही", "ట్రాన్స్‌క్రిప్ట్ అందుబాటులో లేదు", "Transkript Mevcut Değil", "படியெடுப்பு கிடைக்கவில்லை", "轉錄不可用", "Phiên âm không khả dụng", "Hindi Available ang Transcript", 'Trascrizione Non Disponibile'),
"transcript_not_saved_msg": ("The full transcript for this project was not saved.\nOnly projects transcribed after this update have saved transcripts.", "此项目的完整转录未保存。\n仅在此更新之后转录的项目有保存的转录。", "इस प्रोजेक्ट की पूर्ण ट्रांसक्रिप्ट सहेजी नहीं गई।\nकेवल इस अपडेट के बाद ट्रांसक्राइब किए गए प्रोजेक्ट में सहेजी गई ट्रांसक्रिप्ट हैं।", "La transcripción completa no fue guardada.\nSolo los proyectos transcritos después de esta actualización tienen transcripciones guardadas.", "La transcription complète n'a pas été sauvegardée.\nSeuls les projets transcrits après cette mise à jour ont des transcriptions sauvegardées.", "لم يتم حفظ النسخ الكامل لهذا المشروع.\nفقط المشاريع المنسوخة بعد هذا التحديث لديها نسخ محفوظة.", "এই প্রকল্পের সম্পূর্ণ ট্রান্সক্রিপ্ট সংরক্ষিত হয়নি।\nশুধু এই আপডেটের পরে ট্রান্সক্রাইব করা প্রকল্পে সংরক্ষিত ট্রান্সক্রিপ্ট আছে।", "A transcrição completa não foi salva.\nApenas projetos transcritos após esta atualização têm transcrições salvas.", "Полная транскрипция не была сохранена.\nТолько проекты, созданные после этого обновления, имеют сохранённые транскрипции.", "اس پروجیکٹ کی مکمل ٹرانسکرپٹ محفوظ نہیں ہوئی۔\nصرف اس اپ ڈیٹ کے بعد ٹرانسکرائب کیے گئے پروجیکٹس میں محفوظ ٹرانسکرپٹ ہیں۔", "Transkrip lengkap untuk proyek ini tidak disimpan.\nHanya proyek yang ditranskrip setelah pembaruan ini memiliki transkrip tersimpan.", "Das vollständige Transkript wurde nicht gespeichert.\nNur nach diesem Update transkribierte Projekte haben gespeicherte Transkripte.", "このプロジェクトの完全な文字起こしは保存されていません。\nこの更新後に文字起こしされたプロジェクトのみ保存されています。", "The full transcript for this project no save.\nOnly projects wey dem transcribe after this update get saved transcripts.", "النسخ الكامل للمشروع ده مش متحفظ.\nبس المشاريع اللي اتنسخت بعد التحديث ده عندها نسخ متحفظة.", "या प्रकल्पाची पूर्ण ट्रान्सक्रिप्ट जतन केली गेली नाही.\nफक्त या अपडेटनंतर ट्रान्सक्राइब केलेल्या प्रकल्पांमध्ये जतन केलेल्या ट्रान्सक्रिप्ट आहेत.", "ఈ ప్రాజెక్ట్ కోసం పూర్తి ట్రాన్స్‌క్రిప్ట్ సేవ్ చేయబడలేదు.\nఈ అప్‌డేట్ తర్వాత ట్రాన్స్‌క్రైబ్ చేసిన ప్రాజెక్ట్‌లు మాత్రమే సేవ్ చేసిన ట్రాన్స్‌క్రిప్ట్‌లను కలిగి ఉంటాయి.", "Bu projenin tam transkripti kaydedilmedi.\nSadece bu güncellemeden sonra yazıya dökülen projelerin kaydedilmiş transkriptleri var.", "இந்த திட்டத்தின் முழு படியெடுப்பு சேமிக்கப்படவில்லை.\nஇந்த புதுப்பிற்குப் பிறகு படியெடுக்கப்பட்ட திட்டங்கள் மட்டுமே சேமிக்கப்பட்ட படியெடுப்புகளைக் கொண்டுள்ளன.", "此項目的完整轉錄未保存。\n僅在此更新之後轉錄的項目有保存的轉錄。", "Bản phiên âm đầy đủ cho dự án này chưa được lưu.\nChỉ các dự án phiên âm sau bản cập nhật này mới có bản phiên âm đã lưu.", "Hindi na-save ang buong transcript ng proyektong ito.\nMga proyektong na-transcribe pagkatapos ng update na ito lang ang may saved transcripts.", 'La trascrizione completa per questo progetto non è stata salvata.\nSolo i progetti trascritti dopo questo aggiornamento hanno trascrizioni salvate.'),

# ── Login ──
"sign_in": ("Sign In", "登录", "साइन इन", "Iniciar sesión", "Connexion", "تسجيل الدخول", "সাইন ইন", "Entrar", "Войти", "سائن ان", "Masuk", "Anmelden", "ログイン", "Sign In", "تسجيل الدخول", "साइन इन", "సైన్ ఇన్", "Giriş", "உள்நுழை", "登入", "Đăng nhập", "Mag-sign in", 'Accedi'),
"welcome_back": ("Welcome back to La Mia Scribe", "欢迎回到 La Mia Scribe", "La Mia Scribe में वापस स्वागत है", "Bienvenido/a de nuevo", "Bon retour sur La Mia Scribe", "مرحبًا بعودتك إلى La Mia Scribe", "La Mia Scribe-এ ফিরে স্বাগতম", "Bem-vindo/a de volta", "С возвращением в La Mia Scribe", "La Mia Scribe میں واپس خوش آمدید", "Selamat datang kembali", "Willkommen zurück", "La Mia Scribe へようこそ", "Welcome back to La Mia Scribe", "أهلاً بعودتك", "La Mia Scribe मध्ये परत स्वागत", "La Mia Scribe కు తిరిగి స్వాగతం", "La Mia Scribe'a tekrar hoş geldiniz", "La Mia Scribe க்கு மீண்டும் வரவேற்கிறோம்", "歡迎回到 La Mia Scribe", "Chào mừng trở lại", "Maligayang pagbabalik", 'Bentornato/a su La Mia Scribe'),
"username": ("Username:", "用户名：", "उपयोगकर्ता नाम:", "Usuario:", "Identifiant :", "اسم المستخدم:", "ব্যবহারকারীর নাম:", "Usuário:", "Имя пользователя:", "صارف نام:", "Nama Pengguna:", "Benutzername:", "ユーザー名:", "Username:", "اسم المستخدم:", "वापरकर्ता नाव:", "వినియోగదారు పేరు:", "Kullanıcı Adı:", "பயனர்பெயர்:", "用戶名：", "Tên đăng nhập:", "Username:", 'Nome Utente:'),
"password": ("Password:", "密码：", "पासवर्ड:", "Contraseña:", "Mot de passe :", "كلمة المرور:", "পাসওয়ার্ড:", "Senha:", "Пароль:", "پاس ورڈ:", "Kata Sandi:", "Passwort:", "パスワード:", "Password:", "كلمة السر:", "पासवर्ड:", "పాస్‌వర్డ్:", "Şifre:", "கடவுச்சொல்:", "密碼：", "Mật khẩu:", "Password:", 'Password:'),
"enter_username": ("Enter your username", "输入用户名", "अपना उपयोगकर्ता नाम दर्ज करें", "Ingresa tu usuario", "Entrez votre identifiant", "أدخل اسم المستخدم", "আপনার ব্যবহারকারীর নাম লিখুন", "Digite seu usuário", "Введите имя пользователя", "اپنا صارف نام درج کریں", "Masukkan nama pengguna", "Benutzernamen eingeben", "ユーザー名を入力", "Enter your username", "اكتب اسم المستخدم", "तुमचे वापरकर्ता नाव प्रविष्ट करा", "మీ వినియోగదారు పేరు నమోదు చేయండి", "Kullanıcı adınızı girin", "உங்கள் பயனர்பெயரை உள்ளிடவும்", "輸入用戶名", "Nhập tên đăng nhập", "Ilagay ang username", 'Inserisci il nome utente'),
"enter_password": ("Enter your password", "输入密码", "अपना पासवर्ड दर्ज करें", "Ingresa tu contraseña", "Entrez votre mot de passe", "أدخل كلمة المرور", "আপনার পাসওয়ার্ড লিখুন", "Digite sua senha", "Введите пароль", "اپنا پاس ورڈ درج کریں", "Masukkan kata sandi", "Passwort eingeben", "パスワードを入力", "Enter your password", "اكتب كلمة السر", "तुमचा पासवर्ड प्रविष्ट करा", "మీ పాస్‌వర్డ్ నమోదు చేయండి", "Şifrenizi girin", "உங்கள் கடவுச்சொல்லை உள்ளிடவும்", "輸入密碼", "Nhập mật khẩu", "Ilagay ang password", 'Inserisci la password'),
"save_login": ("Save login info", "保存登录信息", "लॉगिन जानकारी सहेजें", "Guardar datos de inicio", "Enregistrer les identifiants", "حفظ بيانات الدخول", "লগইন তথ্য সংরক্ষণ", "Salvar informações de login", "Сохранить данные входа", "لاگ ان معلومات محفوظ کریں", "Simpan info login", "Anmeldedaten speichern", "ログイン情報を保存", "Save login info", "احفظ بيانات الدخول", "लॉगिन माहिती जतन करा", "లాగిన్ సమాచారం సేవ్ చేయి", "Giriş bilgilerini kaydet", "உள்நுழைவு தகவலைச் சேமி", "儲存登入資訊", "Lưu thông tin đăng nhập", "I-save ang login info", 'Salva dati di accesso'),
"create_account": ("Create Account", "创建账户", "खाता बनाएँ", "Crear cuenta", "Créer un compte", "إنشاء حساب", "অ্যাকাউন্ট তৈরি", "Criar conta", "Создать аккаунт", "اکاؤنٹ بنائیں", "Buat Akun", "Konto erstellen", "アカウント作成", "Create Account", "إنشاء حساب", "खाते तयार करा", "ఖాతా సృష్టించు", "Hesap Oluştur", "கணக்கை உருவாக்கு", "建立帳戶", "Tạo tài khoản", "Gumawa ng Account", 'Crea Account'),
"dont_have_account": ("Don't have an account?", "没有账户？", "खाता नहीं है?", "¿No tienes cuenta?", "Pas de compte ?", "ليس لديك حساب؟", "অ্যাকাউন্ট নেই?", "Não tem conta?", "Нет аккаунта?", "اکاؤنٹ نہیں ہے؟", "Belum punya akun?", "Kein Konto?", "アカウントがない？", "You no get account?", "معندكش حساب؟", "खाते नाही?", "ఖాతా లేదా?", "Hesabınız yok mu?", "கணக்கு இல்லையா?", "沒有帳戶？", "Chưa có tài khoản?", "Wala pang account?", 'Non hai un account?'),
"already_have_account": ("Already have an account?", "已有账户？", "पहले से खाता है?", "¿Ya tienes cuenta?", "Déjà un compte ?", "لديك حساب بالفعل؟", "ইতিমধ্যে অ্যাকাউন্ট আছে?", "Já tem conta?", "Уже есть аккаунт?", "پہلے سے اکاؤنٹ ہے؟", "Sudah punya akun?", "Bereits ein Konto?", "アカウントをお持ちですか？", "You don get account?", "عندك حساب؟", "आधीच खाते आहे?", "ఇప్పటికే ఖాతా ఉందా?", "Zaten hesabınız var mı?", "ஏற்கனவே கணக்கு உள்ளதா?", "已有帳戶？", "Đã có tài khoản?", "Mayroon nang account?", 'Hai già un account?'),
"display_name": ("Display Name:", "显示名称：", "प्रदर्शन नाम:", "Nombre para mostrar:", "Nom d'affichage :", "الاسم المعروض:", "ডিসপ্লে নাম:", "Nome de exibição:", "Отображаемое имя:", "ڈسپلے نام:", "Nama Tampilan:", "Anzeigename:", "表示名:", "Display Name:", "الاسم:", "प्रदर्शन नाव:", "ప్రదర్శన పేరు:", "Görünen Ad:", "காட்சிப் பெயர்:", "顯示名稱：", "Tên hiển thị:", "Display Name:", 'Nome Visualizzato:'),
"your_full_name": ("Your full name", "您的全名", "आपका पूरा नाम", "Tu nombre completo", "Votre nom complet", "اسمك الكامل", "আপনার পুরো নাম", "Seu nome completo", "Ваше полное имя", "آپ کا پورا نام", "Nama lengkap Anda", "Ihr vollständiger Name", "フルネーム", "Your full name", "اسمك بالكامل", "तुमचे पूर्ण नाव", "మీ పూర్తి పేరు", "Tam adınız", "உங்கள் முழு பெயர்", "您的全名", "Họ tên đầy đủ", "Buong pangalan mo", 'Il tuo nome completo'),
"confirm_password": ("Confirm Password:", "确认密码：", "पासवर्ड की पुष्टि:", "Confirmar contraseña:", "Confirmer le mot de passe :", "تأكيد كلمة المرور:", "পাসওয়ার্ড নিশ্চিত:", "Confirmar senha:", "Подтвердите пароль:", "پاس ورڈ کی تصدیق:", "Konfirmasi Sandi:", "Passwort bestätigen:", "パスワード確認:", "Confirm Password:", "أكد كلمة السر:", "पासवर्ड पुष्टी:", "పాస్‌వర్డ్ నిర్ధారించు:", "Şifreyi Onayla:", "கடவுச்சொல் உறுதிப்படுத்து:", "確認密碼：", "Xác nhận mật khẩu:", "Kumpirmahin ang Password:", 'Conferma Password:'),
"show": ("Show", "显示", "दिखाएँ", "Mostrar", "Afficher", "إظهار", "দেখান", "Mostrar", "Показать", "دکھائیں", "Tampilkan", "Anzeigen", "表示", "Show", "أظهر", "दाखवा", "చూపు", "Göster", "காட்டு", "顯示", "Hiện", "Ipakita", 'Mostra'),
"hide": ("Hide", "隐藏", "छुपाएँ", "Ocultar", "Masquer", "إخفاء", "লুকান", "Ocultar", "Скрыть", "چھپائیں", "Sembunyikan", "Ausblenden", "非表示", "Hide", "إخفي", "लपवा", "దాచు", "Gizle", "மறை", "隱藏", "Ẩn", "Itago", 'Nascondi'),
"all_fields_required": ("All fields are required.", "所有字段必填。", "सभी फ़ील्ड आवश्यक हैं।", "Todos los campos son obligatorios.", "Tous les champs sont requis.", "جميع الحقول مطلوبة.", "সব ক্ষেত্র প্রয়োজনীয়।", "Todos os campos são obrigatórios.", "Все поля обязательны.", "تمام فیلڈز ضروری ہیں۔", "Semua kolom wajib diisi.", "Alle Felder sind erforderlich.", "すべてのフィールドは必須です。", "All fields na required.", "كل الحقول مطلوبة.", "सर्व फील्ड आवश्यक आहेत.", "అన్ని ఫీల్డ్‌లు అవసరం.", "Tüm alanlar gereklidir.", "அனைத்து புலங்களும் தேவை.", "所有欄位必填。", "Tất cả các trường đều bắt buộc.", "Lahat ng field ay kinakailangan.", 'Tutti i campi sono obbligatori.'),
"passwords_no_match": ("Passwords do not match.", "密码不匹配。", "पासवर्ड मेल नहीं खाते।", "Las contraseñas no coinciden.", "Les mots de passe ne correspondent pas.", "كلمات المرور غير متطابقة.", "পাসওয়ার্ড মেলেনি।", "As senhas não correspondem.", "Пароли не совпадают.", "پاس ورڈ میل نہیں کھاتے۔", "Kata sandi tidak cocok.", "Passwörter stimmen nicht überein.", "パスワードが一致しません。", "Passwords no match.", "كلمات السر مش متطابقة.", "पासवर्ड जुळत नाहीत.", "పాస్‌వర్డ్‌లు సరిపోలడం లేదు.", "Şifreler eşleşmiyor.", "கடவுச்சொற்கள் பொருந்தவில்லை.", "密碼不匹配。", "Mật khẩu không khớp.", "Hindi magkatugma ang mga password.", 'Le password non corrispondono.'),
"enter_both": ("Please enter both username and password.", "请输入用户名和密码。", "कृपया उपयोगकर्ता नाम और पासवर्ड दोनों दर्ज करें।", "Ingresa usuario y contraseña.", "Veuillez entrer identifiant et mot de passe.", "يرجى إدخال اسم المستخدم وكلمة المرور.", "অনুগ্রহ করে ব্যবহারকারীর নাম ও পাসওয়ার্ড লিখুন।", "Insira usuário e senha.", "Введите имя пользователя и пароль.", "براہ کرم صارف نام اور پاس ورڈ درج کریں۔", "Masukkan nama pengguna dan kata sandi.", "Benutzernamen und Passwort eingeben.", "ユーザー名とパスワードを入力してください。", "Abeg enter username and password.", "اكتب اسم المستخدم وكلمة السر.", "कृपया वापरकर्ता नाव आणि पासवर्ड दोन्ही प्रविष्ट करा.", "దయచేసి వినియోగదారు పేరు మరియు పాస్‌వర్డ్ రెండూ నమోదు చేయండి.", "Lütfen kullanıcı adı ve şifre girin.", "பயனர்பெயர் மற்றும் கடவுச்சொல் இரண்டையும் உள்ளிடவும்.", "請輸入用戶名和密碼。", "Vui lòng nhập tên đăng nhập và mật khẩu.", "Pakilagay ang username at password.", 'Inserisci nome utente e password.'),
"join_app": ("Join La Mia Scribe", "加入 La Mia Scribe", "La Mia Scribe से जुड़ें", "Únete a La Mia Scribe", "Rejoindre La Mia Scribe", "انضم إلى La Mia Scribe", "La Mia Scribe-এ যোগ দিন", "Junte-se ao La Mia Scribe", "Присоединяйтесь к La Mia Scribe", "La Mia Scribe میں شامل ہوں", "Bergabung dengan La Mia Scribe", "La Mia Scribe beitreten", "La Mia Scribe に参加", "Join La Mia Scribe", "انضم لـ La Mia Scribe", "La Mia Scribe मध्ये सामील व्हा", "La Mia Scribe లో చేరండి", "La Mia Scribe'a katılın", "La Mia Scribe இல் சேரவும்", "加入 La Mia Scribe", "Tham gia La Mia Scribe", "Sumali sa La Mia Scribe", 'Unisciti a La Mia Scribe'),
"account_created": ("Account Created", "账户已创建", "खाता बनाया गया", "Cuenta creada", "Compte créé", "تم إنشاء الحساب", "অ্যাকাউন্ট তৈরি হয়েছে", "Conta criada", "Аккаунт создан", "اکاؤنٹ بنایا گیا", "Akun Dibuat", "Konto erstellt", "アカウント作成済み", "Account Don Create", "الحساب اتعمل", "खाते तयार झाले", "ఖాతా సృష్టించబడింది", "Hesap Oluşturuldu", "கணக்கு உருவாக்கப்பட்டது", "帳戶已建立", "Tài khoản đã tạo", "Na-create ang Account", 'Account Creato'),

# ── Accessibility ──
"accessibility": ("Accessibility", "辅助功能", "सुलभता", "Accesibilidad", "Accessibilité", "إمكانية الوصول", "অ্যাক্সেসিবিলিটি", "Acessibilidade", "Доступность", "رسائی", "Aksesibilitas", "Barrierefreiheit", "アクセシビリティ", "Accessibility", "إمكانية الوصول", "सुलभता", "ప్రాప్యత", "Erişilebilirlik", "அணுகல்தன்மை", "輔助功能", "Trợ năng", "Accessibility", 'Accessibilità'),
"font_size": ("Font Size", "字体大小", "फ़ॉन्ट आकार", "Tamaño de fuente", "Taille de police", "حجم الخط", "ফন্ট সাইজ", "Tamanho da fonte", "Размер шрифта", "فونٹ سائز", "Ukuran Font", "Schriftgröße", "フォントサイズ", "Font Size", "حجم الخط", "फॉन्ट आकार", "ఫాంట్ పరిమాణం", "Yazı Boyutu", "எழுத்துரு அளவு", "字體大小", "Cỡ chữ", "Laki ng Font", 'Dimensione Carattere'),
"font_type": ("Font Type", "字体类型", "फ़ॉन्ट प्रकार", "Tipo de fuente", "Type de police", "نوع الخط", "ফন্ট টাইপ", "Tipo de fonte", "Тип шрифта", "فونٹ ٹائپ", "Jenis Font", "Schriftart", "フォントタイプ", "Font Type", "نوع الخط", "फॉन्ट प्रकार", "ఫాంట్ రకం", "Yazı Türü", "எழுத்துரு வகை", "字體類型", "Kiểu chữ", "Uri ng Font", 'Tipo di Carattere'),
"color_theme": ("Color Theme", "颜色主题", "रंग थीम", "Tema de color", "Thème de couleur", "سمة اللون", "রঙের থিম", "Tema de cor", "Цветовая тема", "رنگ تھیم", "Tema Warna", "Farbschema", "カラーテーマ", "Color Theme", "لون الثيم", "रंग थीम", "రంగు థీమ్", "Renk Teması", "வண்ணத் தீம்", "色彩主題", "Chủ đề màu", "Tema ng Kulay", 'Tema Colore'),
"colorblind_support": ("Colorblind Support", "色盲支持", "कलर ब्लाइंड सहायता", "Soporte para daltonismo", "Support daltonien", "دعم عمى الألوان", "কালারব্লাইন্ড সাপোর্ট", "Suporte a daltonismo", "Дальтонизм", "رنگ اندھا پن معاونت", "Dukungan Buta Warna", "Farbenblind-Unterstützung", "色覚サポート", "Colorblind Support", "دعم عمى الألوان", "रंगांधत्व समर्थन", "కలర్‌బ్లైండ్ సపోర్ట్", "Renk Körlüğü Desteği", "நிறக்குருடு ஆதரவு", "色盲支持", "Hỗ trợ mù màu", "Suporta sa Color Blind", 'Supporto Daltonismo'),
"cursor_style": ("Cursor Style", "光标样式", "कर्सर शैली", "Estilo del cursor", "Style du curseur", "نمط المؤشر", "কার্সর স্টাইল", "Estilo do cursor", "Стиль курсора", "کرسر اسٹائل", "Gaya Kursor", "Cursor-Stil", "カーソルスタイル", "Cursor Style", "شكل المؤشر", "कर्सर शैली", "కర్సర్ శైలి", "İmleç Stili", "கர்சர் நடை", "游標樣式", "Kiểu con trỏ", "Estilo ng Cursor", 'Stile Cursore'),
"more_options": ("More Options", "更多选项", "अधिक विकल्प", "Más opciones", "Plus d'options", "خيارات إضافية", "আরো অপশন", "Mais opções", "Дополнительно", "مزید اختیارات", "Opsi Lainnya", "Weitere Optionen", "その他のオプション", "More Options", "خيارات تانية", "अधिक पर्याय", "మరిన్ని ఎంపికలు", "Daha Fazla Seçenek", "மேலும் விருப்பங்கள்", "更多選項", "Thêm tùy chọn", "Higit pang Opsyon", 'Altre Opzioni'),
"reduced_motion": ("Reduced Motion", "减少动画", "कम गति", "Movimiento reducido", "Mouvement réduit", "تقليل الحركة", "হ্রাসকৃত গতি", "Movimento reduzido", "Мало анимации", "کم حرکت", "Gerakan Dikurangi", "Weniger Bewegung", "モーション軽減", "Reduced Motion", "حركة أقل", "कमी हालचाल", "తగ్గించిన చలనం", "Azaltılmış Hareket", "குறைந்த இயக்கம்", "減少動畫", "Giảm chuyển động", "Reduced Motion", 'Movimento Ridotto'),
"text_spacing": ("Enhanced Text Spacing", "增强文本间距", "बेहतर टेक्स्ट स्पेसिंग", "Espaciado mejorado", "Espacement amélioré", "تباعد نص محسّن", "উন্নত টেক্সট স্পেসিং", "Espaçamento aprimorado", "Увеличенные интервалы", "بہتر ٹیکسٹ اسپیسنگ", "Jarak Teks Ditingkatkan", "Erweiterter Textabstand", "テキスト間隔拡大", "Better Text Spacing", "تباعد نص أحسن", "सुधारित मजकूर अंतर", "మెరుగైన టెక్స్ట్ స్పేసింగ్", "Gelişmiş Metin Aralığı", "மேம்பட்ட உரை இடைவெளி", "增強文字間距", "Giãn cách văn bản", "Enhanced Text Spacing", 'Spaziatura Testo Migliorata'),
"enhanced_focus": ("Enhanced Focus Indicators", "增强焦点指示", "बेहतर फ़ोकस इंडिकेटर", "Indicadores de enfoque", "Indicateurs de focus améliorés", "مؤشرات تركيز محسّنة", "উন্নত ফোকাস ইন্ডিকেটর", "Indicadores de foco aprimorados", "Улучшенные индикаторы фокуса", "بہتر فوکس انڈیکیٹرز", "Indikator Fokus Ditingkatkan", "Erweiterte Fokusindikatoren", "フォーカス強調", "Better Focus Indicators", "مؤشرات تركيز أحسن", "सुधारित फोकस निर्देशक", "మెరుగైన ఫోకస్ సూచికలు", "Gelişmiş Odak Göstergeleri", "மேம்பட்ட கவன குறிகாட்டிகள்", "增強焦點指示", "Chỉ báo tiêu điểm", "Enhanced Focus Indicators", 'Indicatori di Focus Migliorati'),
"app_language": ("App Language", "应用语言", "ऐप भाषा", "Idioma de la app", "Langue de l'appli", "لغة التطبيق", "অ্যাপ ভাষা", "Idioma do app", "Язык приложения", "ایپ زبان", "Bahasa Aplikasi", "App-Sprache", "アプリの言語", "App Language", "لغة التطبيق", "ॲप भाषा", "యాప్ భాష", "Uygulama Dili", "செயலி மொழி", "應用語言", "Ngôn ngữ ứng dụng", "Wika ng App", "Lingua dell'App"),

# ── Progress / Status ──
"extracting_audio": ("Extracting audio...", "正在提取音频...", "ऑडियो निकाल रहे हैं...", "Extrayendo audio...", "Extraction audio...", "استخراج الصوت...", "অডিও বের করা হচ্ছে...", "Extraindo áudio...", "Извлечение аудио...", "آڈیو نکالا جا رہا ہے...", "Mengekstrak audio...", "Audio wird extrahiert...", "音声を抽出中...", "Extracting audio...", "استخراج الصوت...", "ऑडिओ काढत आहे...", "ఆడియో ఎక్స్‌ట్రాక్ట్ చేస్తోంది...", "Ses çıkarılıyor...", "ஆடியோ பிரித்தெடுக்கிறது...", "正在提取音頻...", "Đang trích xuất âm thanh...", "Kinukuha ang audio...", 'Estrazione audio...'),
"loading_model": ("Loading Whisper model...", "正在加载Whisper模型...", "Whisper मॉडल लोड हो रहा है...", "Cargando modelo Whisper...", "Chargement du modèle Whisper...", "تحميل نموذج Whisper...", "Whisper মডেল লোড হচ্ছে...", "Carregando modelo Whisper...", "Загрузка модели Whisper...", "Whisper ماڈل لوڈ ہو رہا ہے...", "Memuat model Whisper...", "Whisper-Modell wird geladen...", "Whisperモデルを読込中...", "Loading Whisper model...", "تحميل موديل Whisper...", "Whisper मॉडेल लोड होत आहे...", "Whisper మోడల్ లోడ్ అవుతోంది...", "Whisper modeli yükleniyor...", "Whisper மாதிரி ஏற்றப்படுகிறது...", "正在載入Whisper模型...", "Đang tải mô hình Whisper...", "Nilo-load ang Whisper model...", 'Caricamento modello Whisper...'),
"transcription_complete": ("Transcription complete.", "转录完成。", "ट्रांसक्रिप्शन पूर्ण।", "Transcripción completada.", "Transcription terminée.", "اكتمل النسخ.", "ট্রান্সক্রিপশন সম্পন্ন।", "Transcrição concluída.", "Транскрибирование завершено.", "ٹرانسکرپشن مکمل۔", "Transkripsi selesai.", "Transkription abgeschlossen.", "文字起こし完了。", "Transcription don finish.", "النسخ خلص.", "ट्रान्सक्रिप्शन पूर्ण.", "ట్రాన్స్‌క్రిప్షన్ పూర్తయింది.", "Yazıya dökme tamamlandı.", "படியெடுப்பு முடிந்தது.", "轉錄完成。", "Phiên âm hoàn tất.", "Kumpleto na ang transcription.", 'Trascrizione completata.'),
"post_processing_complete": ("Post-processing complete.", "后处理完成。", "पोस्ट-प्रोसेसिंग पूर्ण।", "Post-procesamiento completado.", "Post-traitement terminé.", "اكتملت المعالجة اللاحقة.", "পোস্ট-প্রসেসিং সম্পন্ন।", "Pós-processamento concluído.", "Пост-обработка завершена.", "پوسٹ پروسیسنگ مکمل۔", "Pasca-pemrosesan selesai.", "Nachbearbeitung abgeschlossen.", "後処理完了。", "Post-processing don finish.", "المعالجة اللاحقة خلصت.", "पोस्ट-प्रोसेसिंग पूर्ण.", "పోస్ట్-ప్రాసెసింగ్ పూర్తయింది.", "Son işlem tamamlandı.", "பின் செயலாக்கம் முடிந்தது.", "後處理完成。", "Xử lý hậu kỳ hoàn tất.", "Kumpleto na ang post-processing.", 'Post-elaborazione completata.'),
"cancelled": ("Cancelled.", "已取消。", "रद्द किया गया।", "Cancelado.", "Annulé.", "تم الإلغاء.", "বাতিল হয়েছে।", "Cancelado.", "Отменено.", "منسوخ ہو گیا۔", "Dibatalkan.", "Abgebrochen.", "キャンセルされました。", "Cancelled.", "تم الإلغاء.", "रद्द केले.", "రద్దు చేయబడింది.", "İptal edildi.", "ரத்து செய்யப்பட்டது.", "已取消。", "Đã hủy.", "Kinansela.", 'Annullato.'),
"starting_extraction": ("Starting audio extraction...", "开始提取音频...", "ऑडियो निकालना शुरू...", "Iniciando extracción de audio...", "Début de l'extraction audio...", "بدء استخراج الصوت...", "অডিও এক্সট্রাকশন শুরু...", "Iniciando extração de áudio...", "Начало извлечения аудио...", "آڈیو نکالنا شروع...", "Memulai ekstraksi audio...", "Audio-Extraktion wird gestartet...", "音声抽出を開始...", "Starting audio extraction...", "بدء استخراج الصوت...", "ऑडिओ काढणे सुरू...", "ఆడియో ఎక్స్‌ట్రాక్షన్ ప్రారంభం...", "Ses çıkarma başlatılıyor...", "ஆடியோ பிரித்தெடுப்பு தொடங்குகிறது...", "開始提取音頻...", "Bắt đầu trích xuất âm thanh...", "Sinisimulan ang audio extraction...", 'Inizio estrazione audio...'),
"running_ollama": ("Running Ollama post-processing...", "正在运行Ollama后处理...", "Ollama पोस्ट-प्रोसेसिंग चल रहा है...", "Ejecutando post-procesamiento Ollama...", "Exécution du post-traitement Ollama...", "تشغيل معالجة Ollama...", "Ollama পোস্ট-প্রসেসিং চলছে...", "Executando pós-processamento Ollama...", "Запуск пост-обработки Ollama...", "Ollama پوسٹ پروسیسنگ جاری ہے...", "Menjalankan pasca-pemrosesan Ollama...", "Ollama-Nachbearbeitung wird ausgeführt...", "Ollama後処理を実行中...", "Running Ollama post-processing...", "تشغيل معالجة Ollama...", "Ollama पोस्ट-प्रोसेसिंग चालू आहे...", "Ollama పోస్ట్-ప్రాసెసింగ్ నడుస్తోంది...", "Ollama son işlemi çalışıyor...", "Ollama பின் செயலாக்கம் இயங்குகிறது...", "正在運行Ollama後處理...", "Đang chạy xử lý hậu kỳ Ollama...", "Pinapatakbo ang Ollama post-processing...", 'Esecuzione post-elaborazione Ollama...'),

# ── Dialogs ──
"no_file_loaded": ("No File Loaded", "未加载文件", "कोई फ़ाइल लोड नहीं", "Sin archivo cargado", "Aucun fichier chargé", "لم يتم تحميل ملف", "কোনো ফাইল লোড হয়নি", "Nenhum arquivo carregado", "Файл не загружен", "کوئی فائل لوڈ نہیں", "Tidak Ada File Dimuat", "Keine Datei geladen", "ファイル未読込", "No File Loaded", "مفيش ملف محمل", "कोणतीही फाइल लोड नाही", "ఫైల్ లోడ్ కాలేదు", "Dosya Yüklenmedi", "கோப்பு ஏற்றப்படவில்லை", "未載入檔案", "Chưa tải tệp", "Walang Na-load na File", 'Nessun File Caricato'),
"load_file_message": ("Please load a media file or fetch a YouTube video before transcribing.", "请先加载媒体文件或获取YouTube视频。", "कृपया ट्रांसक्राइब करने से पहले मीडिया फ़ाइल लोड करें या YouTube वीडियो प्राप्त करें।", "Carga un archivo o ingresa un URL de YouTube antes de transcribir.", "Veuillez charger un fichier ou récupérer une vidéo YouTube.", "يرجى تحميل ملف أو جلب فيديو يوتيوب قبل النسخ.", "অনুগ্রহ করে ট্রান্সক্রাইব করার আগে একটি ফাইল লোড করুন।", "Carregue um arquivo ou busque um vídeo do YouTube.", "Загрузите файл или видео с YouTube перед транскрибированием.", "براہ کرم ٹرانسکرائب کرنے سے پہلے فائل لوڈ کریں۔", "Muat file atau ambil video YouTube terlebih dahulu.", "Bitte laden Sie eine Datei oder ein YouTube-Video.", "文字起こし前にファイルを読み込むかYouTube動画を取得してください。", "Abeg load media file or YouTube video first.", "حمل ملف أو فيديو يوتيوب الأول.", "कृपया ट्रान्सक्राइब करण्यापूर्वी फाइल लोड करा.", "దయచేసి ట్రాన్స్‌క్రైబ్ చేయడానికి ముందు ఫైల్ లోడ్ చేయండి.", "Lütfen yazıya dökmeden önce bir dosya yükleyin.", "படியெடுக்கும் முன் கோப்பை ஏற்றவும்.", "請先載入媒體檔案或獲取YouTube影片。", "Vui lòng tải tệp hoặc video YouTube trước.", "Mag-load muna ng file o YouTube video.", 'Carica un file multimediale o scarica un video YouTube prima di trascrivere.'),

# ── Tutorial Navigation ──
"step_of": ("Step {n} of {total}", "第 {n} 步，共 {total} 步", "चरण {n} / {total}", "Paso {n} de {total}", "Étape {n} sur {total}", "الخطوة {n} من {total}", "ধাপ {n} / {total}", "Passo {n} de {total}", "Шаг {n} из {total}", "مرحلہ {n} از {total}", "Langkah {n} dari {total}", "Schritt {n} von {total}", "ステップ {n} / {total}", "Step {n} of {total}", "الخطوة {n} من {total}", "चरण {n} / {total}", "దశ {n} / {total}", "Adım {n} / {total}", "படி {n} / {total}", "步驟 {n} / {total}", "Bước {n} / {total}", "Hakbang {n} ng {total}", 'Passo {n} di {total}'),
"finish": ("Finish", "完成", "समाप्त", "Terminar", "Terminer", "إنهاء", "শেষ", "Finalizar", "Завершить", "ختم", "Selesai", "Fertig", "完了", "Finish", "خلص", "समाप्त", "ముగించు", "Bitir", "முடி", "完成", "Hoàn tất", "Tapusin", 'Fine'),
"previous": ("Previous", "上一步", "पिछला", "Anterior", "Précédent", "السابق", "পূর্ববর্তী", "Anterior", "Назад", "پچھلا", "Sebelumnya", "Zurück", "前へ", "Previous", "السابق", "मागील", "మునుపటి", "Önceki", "முந்தைய", "上一步", "Trước", "Nakaraan", 'Precedente'),

# ── Tutorial Titles ──
"tut_welcome_title": ("Welcome to La Mia Scribe", "欢迎使用 La Mia Scribe", "La Mia Scribe में आपका स्वागत है", "Bienvenido a La Mia Scribe", "Bienvenue sur La Mia Scribe", "مرحبًا بك في La Mia Scribe", "La Mia Scribe-এ স্বাগতম", "Bem-vindo ao La Mia Scribe", "Добро пожаловать в La Mia Scribe", "La Mia Scribe میں خوش آمدید", "Selamat datang di La Mia Scribe", "Willkommen bei La Mia Scribe", "La Mia Scribe へようこそ", "Welcome to La Mia Scribe", "أهلاً بيك في La Mia Scribe", "La Mia Scribe मध्ये स्वागत", "La Mia Scribe కు స్వాగతం", "La Mia Scribe'a Hoş Geldiniz", "La Mia Scribe க்கு வரவேற்கிறோம்", "歡迎使用 La Mia Scribe", "Chào mừng đến La Mia Scribe", "Maligayang pagdating sa La Mia Scribe", 'Benvenuto in La Mia Scribe'),
"tut_load_title": ("Load a Media File", "加载媒体文件", "मीडिया फ़ाइल लोड करें", "Cargar un archivo", "Charger un fichier", "تحميل ملف وسائط", "মিডিয়া ফাইল লোড করুন", "Carregar um arquivo", "Загрузить файл", "میڈیا فائل لوڈ کریں", "Muat File Media", "Mediendatei laden", "メディアファイルを読込", "Load a Media File", "حمل ملف ميديا", "मीडिया फाइल लोड करा", "మీడియా ఫైల్ లోడ్ చేయండి", "Medya Dosyası Yükle", "மீடியா கோப்பு ஏற்றவும்", "載入媒體檔案", "Tải tệp phương tiện", "Mag-load ng Media File", 'Carica un File Multimediale'),
"tut_whisper_title": ("Configure Whisper Settings", "配置Whisper设置", "Whisper सेटिंग्स कॉन्फ़िगर करें", "Configurar Whisper", "Configurer Whisper", "إعداد Whisper", "Whisper সেটিংস কনফিগার", "Configurar Whisper", "Настроить Whisper", "Whisper ترتیبات کنفیگر کریں", "Konfigurasi Whisper", "Whisper konfigurieren", "Whisper設定", "Set Up Whisper", "ظبط إعدادات Whisper", "Whisper सेटिंग्ज कॉन्फिगर करा", "Whisper సెట్టింగ్‌లు కాన్ఫిగర్ చేయండి", "Whisper'ı Yapılandır", "Whisper அமைப்புகளை உள்ளமை", "配置Whisper設定", "Cấu hình Whisper", "I-configure ang Whisper", 'Configura Impostazioni Whisper'),
"tut_ollama_title": ("Ollama Post-Processing", "Ollama后处理", "Ollama पोस्ट-प्रोसेसिंग", "Post-procesamiento Ollama", "Post-traitement Ollama", "معالجة Ollama", "Ollama পোস্ট-প্রসেসিং", "Pós-processamento Ollama", "Пост-обработка Ollama", "Ollama پوسٹ پروسیسنگ", "Pasca-pemrosesan Ollama", "Ollama-Nachbearbeitung", "Ollama後処理", "Ollama Post-Processing", "معالجة Ollama", "Ollama पोस्ट-प्रोसेसिंग", "Ollama పోస్ట్-ప్రాసెసింగ్", "Ollama Son İşlemi", "Ollama பின் செயலாக்கம்", "Ollama後處理", "Xử lý hậu kỳ Ollama", "Ollama Post-Processing", 'Post-Elaborazione Ollama'),
"tut_transcribe_title": ("Transcribe", "转录", "ट्रांसक्राइब करें", "Transcribir", "Transcrire", "النسخ", "ট্রান্সক্রাইব", "Transcrever", "Транскрибировать", "ٹرانسکرائب", "Transkrip", "Transkribieren", "文字起こし", "Transcribe", "النسخ", "ट्रान्सक्राइब", "ట్రాన్స్‌క్రైబ్", "Yazıya Dök", "படியெடு", "轉錄", "Phiên âm", "I-transcribe", 'Trascrivi'),
"tut_review_title": ("Review & Edit", "审阅和编辑", "समीक्षा और संपादन", "Revisar y editar", "Réviser et modifier", "مراجعة وتحرير", "পর্যালোচনা ও সম্পাদনা", "Revisar e editar", "Просмотр и редактирование", "جائزہ اور ترمیم", "Tinjau & Edit", "Überprüfen & Bearbeiten", "確認と編集", "Review & Edit", "مراجعة وتعديل", "पुनरावलोकन आणि संपादन", "సమీక్ష & సవరణ", "İncele & Düzenle", "மதிப்பாய்வு & திருத்தம்", "審閱和編輯", "Xem lại & Chỉnh sửa", "Suriin at I-edit", 'Rivedi e Modifica'),
"tut_export_title": ("Export Your Transcript", "导出转录", "ट्रांसक्रिप्ट निर्यात करें", "Exportar transcripción", "Exporter la transcription", "تصدير النسخ", "ট্রান্সক্রিপ্ট এক্সপোর্ট", "Exportar transcrição", "Экспорт транскрипции", "ٹرانسکرپٹ ایکسپورٹ کریں", "Ekspor Transkrip", "Transkript exportieren", "文字起こしをエクスポート", "Export Transcript", "صدر النسخ", "ट्रान्सक्रिप्ट निर्यात करा", "ట్రాన్స్‌క్రిప్ట్ ఎగుమతి", "Transkripti Dışa Aktar", "படியெடுப்பு ஏற்றுமதி", "匯出轉錄", "Xuất phiên âm", "I-export ang Transcript", 'Esporta la Trascrizione'),
"tut_dashboard_title": ("Dashboard & Project History", "仪表板和项目历史", "डैशबोर्ड और प्रोजेक्ट इतिहास", "Panel y historial de proyectos", "Tableau de bord et historique", "لوحة التحكم وسجل المشاريع", "ড্যাশবোর্ড ও প্রকল্প ইতিহাস", "Painel e histórico", "Панель и история проектов", "ڈیش بورڈ اور پروجیکٹ ہسٹری", "Dasbor & Riwayat Proyek", "Übersicht & Projektverlauf", "ダッシュボードとプロジェクト履歴", "Dashboard & Project History", "لوحة التحكم وسجل المشاريع", "डॅशबोर्ड आणि प्रकल्प इतिहास", "డాష్‌బోర్డ్ & ప్రాజెక్ట్ హిస్టరీ", "Kontrol Paneli & Proje Geçmişi", "டாஷ்போர்டு & திட்ட வரலாறு", "儀表板和項目歷史", "Bảng điều khiển & Lịch sử dự án", "Dashboard at History ng Proyekto", 'Pannello e Cronologia Progetti'),
"tut_a11y_title": ("Accessibility Features", "辅助功能", "सुलभता सुविधाएँ", "Funciones de accesibilidad", "Fonctions d'accessibilité", "ميزات إمكانية الوصول", "অ্যাক্সেসিবিলিটি বৈশিষ্ট্য", "Recursos de acessibilidade", "Функции доступности", "رسائی خصوصیات", "Fitur Aksesibilitas", "Barrierefreiheit-Funktionen", "アクセシビリティ機能", "Accessibility Features", "ميزات إمكانية الوصول", "सुलभता वैशिष्ट्ये", "ప్రాప్యత ఫీచర్లు", "Erişilebilirlik Özellikleri", "அணுகல்தன்மை அம்சங்கள்", "輔助功能特性", "Tính năng trợ năng", "Accessibility Features", 'Funzioni di Accessibilità'),
"tut_shortcuts_title": ("Keyboard Shortcuts", "键盘快捷键", "कीबोर्ड शॉर्टकट", "Atajos de teclado", "Raccourcis clavier", "اختصارات لوحة المفاتيح", "কীবোর্ড শর্টকাট", "Atalhos de teclado", "Горячие клавиши", "کی بورڈ شارٹ کٹس", "Pintasan Keyboard", "Tastaturkürzel", "キーボードショートカット", "Keyboard Shortcuts", "اختصارات الكيبورد", "कीबोर्ड शॉर्टकट", "కీబోర్డ్ షార్ట్‌కట్‌లు", "Klavye Kısayolları", "விசைப்பலகை குறுக்குவழிகள்", "鍵盤快捷鍵", "Phím tắt", "Keyboard Shortcuts", 'Scorciatoie da Tastiera'),
"tut_done_title": ("You're All Set!", "设置完成！", "सब तैयार है!", "¡Todo listo!", "C'est parti !", "كل شيء جاهز!", "সব প্রস্তুত!", "Tudo pronto!", "Всё готово!", "سب تیار ہے!", "Semua Siap!", "Alles fertig!", "準備完了！", "You Don Ready!", "كل حاجة جاهزة!", "सर्व तयार!", "అంతా సిద్ధం!", "Her Şey Hazır!", "எல்லாம் தயார்!", "全部設定完成！", "Sẵn sàng!", "Handa ka na!", 'Tutto Pronto!'),
}

# Build the nested TRANSLATIONS dict from compact format
TRANSLATIONS = {}
for _i, _lang in enumerate(_L):
    TRANSLATIONS[_lang] = {_key: _vals[_i] for _key, _vals in _T.items()}
